### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by buchanae** [bmeg/gaea#24]
I was excited to see the simplicity of the "usage" instructions in the README, but was sad to quickly run into a missing dependency:

```
$GOPATH/src/github.com/bmeg/gaia/bin/gaia init
/bin/sh: 1: sbt: not found
```

Ok, easy enough, just google `install sbt` and copy/paste a few apt commands.

But then, an error:
```
[error] Expected ID character
[error] Not a valid command: command (similar: loadp)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: command (similar: commands, cleanupCommands, clean)
[error] command/run migrate --config resources/config/gaia.yaml
[error]        ^
```

**Comment by prismofeverything** [comment]
You are witnessing the previous scala version (which still inhabits the
same repo). The new code (and README) is on the `flow` branch.

  https://github.com/bmeg/gaia/tree/flow

It has been a lengthy pull request.

I'm not sure the README is totally up to date, I will have to check it out
when I'm back in.
