### ISSUE TITLE
output features

### ISSUE THREAD

**Issue by adamstruck** [bmeg/gaea#30]
Two new features:

1) all outputs (final and intermediate) should be able to be specified in the processes file
2) specifying outputs in the process file is optional. If omitted a URI will automatically be assigned

**Comment by prismofeverything** [comment]
Omitted outputs now being generated automatically: https://github.com/bmeg/gaia/commit/d1f71de642ef7857d6da0aec12acf2ab938b702d

**Comment by prismofeverything** [comment]
Okay, all working now.
